JWT_KEY: fH8bJO/zNfPYKqRPjwdyydnaEb54nPXAUZMibkb35M8=
# Configure the datasource for connecting to MySQL database
spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pAqndWDxKcYTWSXddwmzhUYtcQghsXdp
  jpa:
    hibernate:
      # Automatically create and drop the database schema on startup
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        # Enable pretty-printing of SQL queries for better readability
        format_sql: true

    # Specify the database type
    database: mysql
    # Set the Hibernate dialect for MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
